migrate script to entry function
starcoinorg/starcoin-framework pull request #142
Opened 2022-09-22 13:58 UTC by 0xpause

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: resolve #129

## What is the new behavior?

-
-
-

## Other information

2022-09-22 14:38 UTC, jolestar approved these changes

2022-09-22 14:43 UTC, jolestar commented
https://github.com/starcoinorg/starcoin-framework/issues/129 这个应该没有全部迁移吧？

2022-09-22 14:47 UTC, 0xpause commented
> #129 这个应该没有全部迁移吧？

应该没有了。 主要的都是旧 DAO 相关的一些 module，目前没有迁移； 还有一个 StdlibUpgradeScripts， 没有什么可以迁移了。

2022-09-22 14:51 UTC, jolestar commented
> > #129 这个应该没有全部迁移吧？
> 
> 应该没有了。 主要的都是旧 DAO 相关的一些 module，目前没有迁移； 还有一个 StdlibUpgradeScripts， 没有什么可以迁移了。

NFT.move/Oracle.move/Block.move 里还有

2022-09-23 00:32 UTC, jolestar commented on sources/Account.move
> +    public(script) fun create_account_with_initial_amount_entry<TokenType: store>(account: signer, fresh_address: address, _auth_key: vector<u8>, initial_amount: u128)
这个方法就没必要了，`_auth_key` 参数已经废弃。

2022-09-23 00:32 UTC, jolestar commented on sources/Account.move
> +    public(script) fun create_account_with_initial_amount_v2_entry<TokenType: store>(account: signer, fresh_address: address, initial_amount: u128)
这个可以改成 `create_account_with_initial_amount_entry` 了

2022-09-23 00:32 UTC, jolestar commented on sources/Block.move
> +    public (script) fun checkpoint_entry(_account: signer){
这个是不是直接挪到 `Block module` 中。另外 CheckpointScript 是这次 v12 新增的 module，可以考虑直接删掉。

2022-09-23 00:32 UTC, jolestar commented on sources/NFT.move
> +    public(script) fun accept_entry<NFTMeta: copy + store + drop, NFTBody: store>(sender: signer) {
`xxx_entry` 方法可以都挪到 NFT module 中

2022-09-23 00:32 UTC, jolestar commented on sources/Oracle.move
> +    public(script) fun register_oracle_entry<OracleT: copy+store+drop>(sender: signer, precision: u8){
这些 `entry` 方法也可以挪到 `PriceOracle` module 中了。

2022-09-23 00:32 UTC, jolestar commented on sources/PackageTxnManager.move
> +        public(script) fun convert_TwoPhaseUpgrade_to_TwoPhaseUpgradeV2_entry(account: signer, package_address: address) acquires TwoPhaseUpgrade {
这个方法是一个旧版本升级的方法，可以废弃掉了，感觉也没必要改了。

2022-09-23 00:35 UTC, jolestar requested changes
XXXScript module 里加 `entry` 方法没意义，加 `xxx_entry` 方法的目的是让 entry  方法和相关的 module 放在一起。

2022-09-23 15:43 UTC, 0xpause commented on sources/PackageTxnManager.move
> +        public(script) fun convert_TwoPhaseUpgrade_to_TwoPhaseUpgradeV2_entry(account: signer, package_address: address) acquires TwoPhaseUpgrade {
fixed

2022-09-23 15:43 UTC, 0xpause commented on sources/Oracle.move
> +    public(script) fun register_oracle_entry<OracleT: copy+store+drop>(sender: signer, precision: u8){
fixed

2022-09-23 15:57 UTC, 0xpause commented on sources/Account.move
> +    public(script) fun create_account_with_initial_amount_entry<TokenType: store>(account: signer, fresh_address: address, _auth_key: vector<u8>, initial_amount: u128)
fixed

2022-09-23 15:57 UTC, 0xpause commented on sources/Account.move
> +    public(script) fun create_account_with_initial_amount_v2_entry<TokenType: store>(account: signer, fresh_address: address, initial_amount: u128)
已修改

2022-09-23 16:00 UTC, jolestar approved these changes

2022-09-24 14:27 UTC, merged