Complete DAOSpace
starcoinorg/starcoin-framework pull request #80
Opened 2022-08-02 08:06 UTC by WGB5445

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

2022-08-02 12:14 UTC, WGB5445 commented
主要有两个变动：
1. MemberEvent 和 GrantEvent 去掉泛型
2. GrantEvent 去掉泛型后，增加plugin 字段，需要 Struct tag ，暂时用 token_code代替，需要 Plugin 带有 Store

2022-08-02 12:30 UTC, baichuan3 commented
去掉泛型是要解决什么问题？

2022-08-02 12:35 UTC, WGB5445 commented
> 去掉泛型是要解决什么问题？

因为在获取 Event 时如果携带泛型，需要先知道泛型才能抓取 Event 
在 CreatDao 时，不能事先知道泛型参数，所以没有办法实时自动获取

2022-08-02 13:13 UTC, jolestar commented on sources/daospace/DAOSpace.move
> +        token: Token::TokenCode
感觉这个用 TokenCode 代替有点怪异。DAOT 可以消除，但感觉 `phantom PluginT ,phantom TokenT` 不能消除

2022-08-02 13:14 UTC, jolestar commented on sources/daospace/DAOSpace.move
> +        token: Token::TokenCode
如果是逻辑上多余的，我们就消除。但如果不多余，还是不要消除。我们在过滤的地方想办法吧。 @wubuku

2022-08-02 13:14 UTC, WGB5445 commented on sources/daospace/DAOSpace.move
> +        token: Token::TokenCode
> 感觉这个用 TokenCode 代替有点怪异。DAOT 可以消除，但感觉 `phantom PluginT ,phantom TokenT` 不能消除

可能不太好查？只能每个Plugin 和 Token都去拉一遍

2022-08-02 13:25 UTC, jolestar commented on sources/daospace/DAOSpace.move
> +        token: Token::TokenCode
这是 offchain 的过滤机制上的问题，优先考虑合约设计的合理性。

2022-08-02 13:30 UTC, WGB5445 commented on sources/daospace/DAOSpace.move
> +        token: Token::TokenCode
> 这是 offchain 的过滤机制上的问题，优先考虑合约设计的合理性。

这里还有一个问题 ，如果整体的 Event strcut 带 DAOT 可以支持一个 DAO 账号创建多个 DAO (是要不要去除 phantom DAOT 的问题)
去掉 `phantom PluginT ,phantom TokenT` 的改动也符合合约设计

2022-08-02 15:13 UTC, jolestar commented on sources/daospace/DAOSpace.move
> +        token: Token::TokenCode
这个不用支持，一个 DAO 账号就一个 DAO，这样符合逻辑。

2022-08-03 02:00 UTC, baichuan3 commented on sources/daospace/DAOSpace.move
> +            plugin: Token::token_code<PluginT>(),
非Token类型的资源，调用Token::token_code会返回什么结果，报错吗，还是空值？

2022-08-03 03:07 UTC, jolestar commented on sources/daospace/DAOSpace.move
> +            plugin: Token::token_code<PluginT>(),
现在不会报错，但未来想修改实现，不通过 native 方法，可能会报错。

2022-08-03 03:20 UTC, welbon approved these changes

2022-08-03 03:27 UTC, baichuan3 commented on sources/daospace/DAOSpace.move
> +            plugin: Token::token_code<PluginT>(),
那把token_code都移除掉，现在取的值也不对，不过有个问题，就是offchain如何实现插件和过滤 @WGB5445 @jolestar

2022-08-03 03:30 UTC, WGB5445 commented on sources/daospace/DAOSpace.move
> +            plugin: Token::token_code<PluginT>(),
> 非Token类型的资源，调用Token::token_code会返回什么结果，报错吗，还是空值？

只要资源拥有 Store 能力，调用 `Token::token_code` 显示的是该 `struct` 的 `address` 、`module` 名、`struct` 名

2022-08-03 03:32 UTC, jolestar commented on sources/daospace/DAOSpace.move
> +            plugin: Token::token_code<PluginT>(),
> 那把token_code都移除掉，现在取的值也不对，不过有个问题，就是offchain如何实现插件和过滤 @WGB5445 @jolestar

过滤 Event 吗？这块如果要实现通配过滤的话要修改一下 block filter.

2022-08-03 03:34 UTC, WGB5445 commented on sources/daospace/DAOSpace.move
> +            plugin: Token::token_code<PluginT>(),
> > 非Token类型的资源，调用Token::token_code会返回什么结果，报错吗，还是空值？
> 
> 只要资源拥有 Store 能力，调用 `Token::token_code` 显示的是该 `struct` 的 `address` 、`module` 名、`struct` 名

这个功能以后也会改掉么 @jolestar

2022-08-03 03:34 UTC, jolestar requested changes
需要修改下

2022-08-03 03:38 UTC, baichuan3 commented on sources/daospace/DAOSpace.move
> +            plugin: Token::token_code<PluginT>(),
> > 非Token类型的资源，调用Token::token_code会返回什么结果，报错吗，还是空值？
> 
> 只要资源拥有 Store 能力，调用 `Token::token_code` 显示的是该 `struct` 的 `address` 、`module` 名、`struct` 名

现在就支持获取任意具备store能力的resource的 type tag能力吗？跟我之前的理解还不太一样，我理解只有Token类型的Resource才能通过Token::token_code获取到type tag， @jolestar 确认下

2022-08-03 06:12 UTC, jolestar commented on sources/daospace/DAOSpace.move
> +            plugin: Token::token_code<PluginT>(),
> 现在就支持获取任意具备store能力的resource的 type tag能力吗？跟我之前的理解还不太一样，我理解只有Token类型的Resource才能通过Token::token_code获取到type tag， @jolestar 确认下

Token::token_code 现在实际上没有判断是否是 Token 类型，它只是一个 native 方法，返回 struct 的类型名。

2022-08-03 06:14 UTC, jolestar commented on sources/daospace/DAOSpace.move
> +            plugin: Token::token_code<PluginT>(),
这里有个 issue 计划解决这个问题 https://github.com/starcoinorg/starcoin-framework/issues/18

2022-08-03 07:11 UTC, WGB5445 commented on sources/daospace/DAOSpace.move
> +            plugin: Token::token_code<PluginT>(),
> > 现在就支持获取任意具备store能力的resource的 type tag能力吗？跟我之前的理解还不太一样，我理解只有Token类型的Resource才能通过Token::token_code获取到type tag， @jolestar 确认下
> 
> Token::token_code 现在实际上没有判断是否是 Token 类型，它只是一个 native 方法，返回 struct 的类型名。

也就是说以后 Token::token_code 会变为一个 `只能返回 Token `类型的方法么？
那么本次的改动恢复为带有泛型 Event，修改 Event filter 机制来解决这个问题？

2022-08-03 12:16 UTC, baichuan3 approved these changes

2022-08-03 13:31 UTC, jolestar commented on sources/daospace/DAOSpace.move
> +            plugin: Token::token_code<PluginT>(),
> > > 现在就支持获取任意具备store能力的resource的 type tag能力吗？跟我之前的理解还不太一样，我理解只有Token类型的Resource才能通过Token::token_code获取到type tag， @jolestar 确认下
> > 
> > 
> > Token::token_code 现在实际上没有判断是否是 Token 类型，它只是一个 native 方法，返回 struct 的类型名。
> 
> 也就是说以后 Token::token_code 会变为一个 `只能返回 Token `类型的方法么？ 那么本次的改动恢复为带有泛型 Event，修改 Event filter 机制来解决这个问题？

对

2022-08-03 13:36 UTC, jolestar approved these changes

2022-08-03 13:36 UTC, merged